### ISSUE TITLE
Dicas

### ISSUE THREAD

**Issue by TiagoCavalcante** [fernandoarmonellifiedler/personal-projects#2]
Tem algumas dicas que eu quero te dar @fernandoarmonellifiedler:
- deixe as notas com formato md porque assim tem como formata-las;
- renomeie o arquivo modelo.html para index.html;
- renomeie a pasta cartas para img (é um pattern);
- separe os arquivos css e js em pastas;
- ao invés da tag section no arquivo modelo.html use a tag main (essa tag serve para o conteúdo principal);
- utilize const para variáveis em que o valor não mudará coma as variáveis *num*, *res* e *lista* do modelo.html;
- no arquivo README.md explique o que este projeto é;
- modificar o atributo lang para es no modelo.html

**Comment by fernandoarmonellifiedler** [comment]
Dicas totalmente aceitas! Obrigado Tiago, estarei aplicando elas na brevidade.
